spring.application.name=el-habashy-back

spring.datasource.url=jdbc:postgresql://localhost:5432/auction_platform
spring.datasource.username=postgres
spring.datasource.password=password

spring.flyway.user=postgres
spring.flyway.password=password
spring.flyway.enabled=true

spring.flyway.clean-disabled=false
