spring.application.name=el-habashy-back

server.port=${PORT:8080}

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.user=${JDBC_DATABASE_USERNAME}
spring.flyway.password=${JDBC_DATABASE_PASSWORD}

